#!/usr/bin/env python
#-*- encoding: utf-8 -*-
import sys
import os

try:
    import jira
except ImportError:
    print('Package jira-python not found, please install required dependencies')
    sys.exit(1)

__author__ = "Damian Kęska"
__license__ = "LGPLv3"
__maintainer__ = "Damian Kęska"
__copyright__ = "Copyleft by FINGO Team"

# get current working directory to include local files (debugging mode)
t = sys.argv[0].replace(os.path.basename(sys.argv[0]), "") + "src/"

if os.path.isdir(t):
    sys.path.append(t)
    
import libjiralogtime
libjiralogtime.runInstance(True)